### ISSUE TITLE
Apartado 3 - Programación Contra la Base de Datos

### ISSUE THREAD

**Issue by javierdesant** [javierdesant/Titanic-DB-Rescue#4]
# Apartado 3: Programación Contra la Base de Datos

### Descripción
Completar los métodos en Java para interactuar con la base de datos utilizando JDBC y Hibernate. Implementar funcionalidades según las especificaciones del enunciado.

#### JDBC
- [x] Descargar y cargar el proyecto Maven desde GitHub:
  - Repositorio: https://github.com/bbddetsisi/practica-bd2425-jdbc

- [x] Completar los siguientes métodos:
  - [x] **`nuevoPlaneta(String nombre, double masa, int radio, String sistema)`**: Añadir exoplanetas de la tabla proporcionada a la base de datos.
  - [x] **`listaPasajerosCabina(String cubierta, int cabina, String lado)`**: Mostrar pasajeros de la cabina `A-60-S` en criosueño.
  - [x] **`listaOrigenes()`**: Mostrar sistemas, planetas y el número de pasajeros procedentes de cada planeta.

#### Hibernate
- [x] Descargar y cargar el proyecto Maven desde GitHub:
  - Repositorio: https://github.com/bbddetsisi/practica-bd2425-hibernate

- [x] Configurar el servidor de MySQL e inicializar la base de datos.

- [x] Implementar las funciones relacionadas con el mapeo de datos y la interacción con Hibernate.

### Criterios de Finalización
- [x] Los métodos deben estar probados y cumplir con los requisitos funcionales del enunciado.
- [x] El código debe seguir buenas prácticas de programación y ser legible.
- [x] La base de datos debe integrarse correctamente con las implementaciones JDBC y Hibernate.

**Comment by JhonyRetro** [comment]
Todo bug corregido, voy a cerrar la issue
