### ISSUE TITLE
Definir el modelo ER

### ISSUE THREAD

**Issue by javierdesant** [javierdesant/Titanic-DB-Rescue#5]
Hay varios detalles todavía por corregir en el modelo, que ya se contemplan en el paso a tablas:

- [x] Las cabinas sólo pueden tener asignadas un único robot de limpieza.
- [x] El personal sólo puede dirigir una única zona de entretenimiento.
- [x] Un pasajero sólo puede tener un único tutor.
- [x] La entidad `Atmósferas` es en realidad una relación N:M.

También habría que:

- [x] Revisar los nombres de las relaciones.
- [x] #6

**Comment by javierdesant** [comment]
Recordad actualizar ambos archivos del modelo tras realizar algún cambio. (Tanto el .erdplus como el .png)

**Comment by javierdesant** [comment]
- [ ] Convertir `Planeta` a una entidad fuerte eliminando `Sistema` y asumiendo el nombre del sistema como clave de `Planeta`.

**Comment by Cafileiro** [comment]
Se ha creado un pull request con la posible respuesta ====> #7

**Comment by javierdesant** [comment]
En las relaciones normales como esta, se debería usar **N** en vez de **M** en la cardinalidad máxima:
![imagen](https://github.com/user-attachments/assets/c84af557-9c1d-4181-b2d1-3b772b599e85)

Sé que Erdplus te lo pone por defecto como M, pero porfa especifícalo. Sólo se usa M cuando una cardinalidad máxima ya es N (relaciones N:M).

Por ejemplo aquí hay una cardinalidad que deberíamos cambiar:
![imagen](https://github.com/user-attachments/assets/53b11ae5-d40a-4b80-806e-6c24e4367406)

> [!WARNING]
> - [ ] También hay que ponerle nombre a esa relación, es una typo.

**Comment by javierdesant** [comment]
> [!WARNING]
> - [ ] Esta relación es N:M, hay que cambiarla.

![imagen](https://github.com/user-attachments/assets/edf84083-40dd-4120-bd69-3b47c92f124d)

**Comment by gomago43** [comment]
¿Esto no esta separados por schemas no?, porque en el apartado 3  la parte de Hibernate hay que hacerlo en un nuevo schema.

**Comment by Cafileiro** [comment]
se ha creado una pull request con los cambios ==> #9
